stages:
  - test
  - deploy

lint:
  image: library/node:latest
  stage: test
  script:
    - npm install
    - npm run pretty:lint

pages:
  image: library/node:latest
  stage: deploy
  script:
    - npm install
    - npm run docs:compile
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG

publish:
  image: library/node:latest
  stage: deploy
  script:
    - npm install
    - npm publish --verbose --access public
  rules:
    - if: $CI_COMMIT_TAG
