stages:
  - test
  - deploy

lint:
  image: quay.imanuel.dev/dockerhub/library---node:latest
  stage: test
  script:
    - npm install
    - npm run lint

pages:
  stage: deploy
  script:
    - mkdir public
    - cp *.css public/
    - cp *.js public/
    - cp *.html public/
    - cp *.png public/
    - cp *.ico public/
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG

publish:
  stage: deploy
  script:
    - npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
    - npm publish --verbose
  rules:
    - if: $CI_COMMIT_TAG