stages:
  - test
  - deploy

lint:
  image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/oven/bun:alpine
  stage: test
  script:
    - bun install
    - bun run pretty:lint

pages:
  image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/oven/bun:alpine
  stage: deploy
  script:
    - bun install
    - bun run docs:compile
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG

publish:
  image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/oven/bun:alpine
  stage: deploy
  script:
    - bun install
    - bun publish --verbose --access public
  rules:
    - if: $CI_COMMIT_TAG
