stages:
  - test
  - deploy

lint:
  image: library/node:latest
  stage: test
  script:
    - npm install
    - npm run lint

pages:
  image: library/node:latest
  stage: deploy
  script:
    - npm install
    - npm run compile:cosmo
    - mkdir public
    - cp cosmo.css public/
    - cp docs.css public/
    - cp *.js public/
    - cp *.html public/
    - cp *.png public/
    - cp *.svg public/
    - cp -r fonts public/
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG

publish:
  image: library/node:latest
  stage: deploy
  script:
    - npm install
    - npm publish --verbose --access public
  rules:
    - if: $CI_COMMIT_TAG
